[package]
name = "dirpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1.0"
bytes = "1.5"
tokio = { version = "1", features = ["full"]}