[package]
name = "dirpc"
version = "0.1.1"
edition = "2021"

[lib]

[dependencies]
dirpc_proc_macro = { path = "../dirpc_proc_macro" }
serde = { version = "1", features = ["derive"]}
serde_json = "1.0"
flexbuffers = "2.0"
bytes = "1.5"
tokio = { version = "1", features = ["full"]}
anyhow = "1"